### PR TITLE
Replace deprecated collections::Bound with ops::Bound

### PR DESCRIPTION
**Pull request by bstrie**

### CODE REVIEW

**Comment by JP-Ellis** [comment]
Thanks for this!  There's currently a big rewrite going on in another pull request which I hope to get merged soon (and when I have time).  I'll then include your PR :smile:

**Comment by JP-Ellis** [comment]
Are you able to updated your PR to resolve conflicts with the most recent changes?

**Comment by b05902132** [comment]
I can merge that later.

**Comment by bstrie** [comment]
Rebased.

**Comment by JP-Ellis** [comment]
Thanks!  I'll update the package the crate version and publish the new one soon :grin:

**Pull request merged**
