### PR TITLE
Remove some unsafe blocks

### PR DESCRIPTION
**Pull request by b05902132**
I saw issue #10 and tried to remove some unsafe blocks that are easy to remove.

They are IntoIter::next() and clear().

### CODE REVIEW

**Comment by b05902132** [comment]
By the way I don't think most unsafe blocks can be removed (easily).
SkipNode has pointers that points to value it owns;
because owned values have the same lifetime as the owner,
the pointers needs to have the same lifetime as the owner,
which AFAIK is not possible in safe rust.

**Comment by JP-Ellis** [comment]
Thanks so much for the pull request!

Could you run `cargo fmt` as well to make sure that the code is all consistent?

EDIT: I see you're still pushing things to the branch.  Let me know when you're ready for me to merge thing :+1:

**Comment by b05902132** [comment]
The forced push was for rustfmt.

Also I forgot to check whether implementing Drop will introduce UB in unsafe blocks...
Will check later.

**Comment by JP-Ellis** [comment]
Yeah, with the drop implementation, I recall this being needed for some reason due to the unusual ownership but it is possible this is no longer needed.  I believe the tests should cover everything, but perhaps it's worth checking there isn't some memory leak?

**Comment by b05902132** [comment]
It was due to IntoIter, which I rewrote so Rust no longer stops Drop from being implemented now.

I was worried that remove may unexpected drop something in unsafe code.

**Comment by b05902132** [comment]
I just recalled that even without implementing Drop, Rust drops all owned values anyway.
If something will be dropped twice now, it should already have been dropped twice before.

**Comment by JP-Ellis** [comment]
Thanks for this!  I've merged the changes.

**Pull request merged**
